/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Interfaces.InterfazRegistarReporteDeEspia;
import Modelo.Espiatienepartido;
import java.text.SimpleDateFormat;

/**
 *
 * @author manuel
 */
public class PanelEspia extends javax.swing.JPanel {

    private InterfazRegistarReporteDeEspia unaInterfazRegistarReporteDeEspia;
    /**
     * Creates new form PanelEspia
     */
    public PanelEspia(InterfazRegistarReporteDeEspia unaInterfazRegistarReporteDeEspia) {
        this. unaInterfazRegistarReporteDeEspia=unaInterfazRegistarReporteDeEspia;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblEquipoVisitante = new javax.swing.JLabel();
        lblEquipoLocal = new javax.swing.JLabel();
        lblNoJornada = new javax.swing.JLabel();
        lblTemporada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReporte = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("jLabel1");

        jLabel6.setText("jLabel1");

        jLabel1.setText("Temporada");

        jLabel3.setText("No Jornada");

        jLabel4.setText("Equipo Local");

        jLabel5.setText("Equipo Visitante");

        jLabel7.setText("Fecha");

        lblFecha.setText("jLabel1");

        lblEquipoVisitante.setText("jLabel1");

        lblEquipoLocal.setText("jLabel1");

        lblNoJornada.setText("jLabel1");

        lblTemporada.setText("jLabel1");

        txtReporte.setColumns(20);
        txtReporte.setRows(5);
        jScrollPane1.setViewportView(txtReporte);

        jButton1.setText("Guardar Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEquipoVisitante)
                            .addComponent(lblFecha)
                            .addComponent(lblTemporada)
                            .addComponent(lblNoJornada)
                            .addComponent(lblEquipoLocal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTemporada)
                            .addGap(12, 12, 12)
                            .addComponent(lblNoJornada)
                            .addGap(18, 18, 18)
                            .addComponent(lblEquipoLocal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblEquipoVisitante)
                            .addGap(18, 18, 18)
                            .addComponent(lblFecha))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

                

        String []s = lblFecha.getText().split("-");
                
        java.sql.Date fecha;
        fecha = new java.sql.Date(Integer.parseInt(s[0])-1900, Integer.parseInt(s[1])-1, Integer.parseInt(s[2]));
        System.out.println("REPORTEISHON"+txtReporte.getText());
        unaInterfazRegistarReporteDeEspia.guardarReporte(lblTemporada.getText(),lblNoJornada.getText(),lblEquipoLocal.getText(),
                lblEquipoVisitante.getText(),fecha,txtReporte.getText());
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEquipoLocal;
    private javax.swing.JLabel lblEquipoVisitante;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNoJornada;
    private javax.swing.JLabel lblTemporada;
    private javax.swing.JTextArea txtReporte;
    // End of variables declaration//GEN-END:variables


    public void cargarLabels(Espiatienepartido unEspiatienepartido){
    
        if (unEspiatienepartido!=null) {
            
                    
            lblEquipoLocal.setText(unEspiatienepartido.getEquipolocal());
        
            
            lblEquipoVisitante.setText(unEspiatienepartido.getEquipovisitante());
        
            lblFecha.setText(unEspiatienepartido.getFecha().toString());
        
            lblNoJornada.setText(String.valueOf(unEspiatienepartido.getNojornada()));
        
            lblTemporada.setText(unEspiatienepartido.getTemporada());
            
        }



    }

}
