/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 23 23:12:22 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package DAOImpl;

import Modelo.Estado;
import Modelo.EstadoKey;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import DAO.EstadoDAO;

/**
 * This class provides methods to populate DB Table of Estado
 */
public class EstadoDAOImpl implements EstadoDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Estado ("
        + "nombreEstado"
        + ") VALUES (?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "nombreEstado "
        + "FROM Estado WHERE "
        + "nombreEstado = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Estado SET "
        + "WHERE "
        + "nombreEstado = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Estado WHERE "
        + "nombreEstado = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Estado bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getNombreestado());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Estado load(EstadoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getNombreestado());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Estado) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Estado bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getNombreestado());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(EstadoKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getNombreestado());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Estado> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Estado>();
        while (rs.next()) {
            Estado bean = new Estado();
            bean.setNombreestado(rs.getString("nombreEstado"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}