/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 23 23:08:23 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package Modelo;

import java.util.Date;

/*
 * For Table espiaTienePartido
 */
public class Espiatienepartido implements java.io.Serializable, Cloneable {
    private EspiatienepartidoKey _key = new EspiatienepartidoKey();

    /* aliasEspia, PK */
    protected String aliasespia;

    /* temporada, PK */
    protected String temporada;

    /* noJornada, PK */
    protected int nojornada;

    /* equipoLocal, PK */
    protected String equipolocal;

    /* equipoVisitante, PK */
    protected String equipovisitante;

    /* fecha */
    protected java.util.Date fecha;

    /* reporte */
    protected String reporte;

    /* Return the key object. */

    public Espiatienepartido() {
    }

    public Espiatienepartido(String aliasespia, String temporada, int nojornada, String equipolocal, String equipovisitante, Date fecha) {
        this.aliasespia = aliasespia;
        this.temporada = temporada;
        this.nojornada = nojornada;
        this.equipolocal = equipolocal;
        this.equipovisitante = equipovisitante;
        this.fecha = fecha;
    
    }
    
    
    public EspiatienepartidoKey getKeyObject() {
        return _key;
    }

    /* aliasEspia, PK */
    public String getAliasespia() {
        return aliasespia;
    }

    /* aliasEspia, PK */
    public void setAliasespia(String aliasespia) {
        this.aliasespia = aliasespia;
        _key.setAliasespia(aliasespia);
    }

    /* temporada, PK */
    public String getTemporada() {
        return temporada;
    }

    /* temporada, PK */
    public void setTemporada(String temporada) {
        this.temporada = temporada;
        _key.setTemporada(temporada);
    }

    /* noJornada, PK */
    public int getNojornada() {
        return nojornada;
    }

    /* noJornada, PK */
    public void setNojornada(int nojornada) {
        this.nojornada = nojornada;
        _key.setNojornada(nojornada);
    }

    /* equipoLocal, PK */
    public String getEquipolocal() {
        return equipolocal;
    }

    /* equipoLocal, PK */
    public void setEquipolocal(String equipolocal) {
        this.equipolocal = equipolocal;
        _key.setEquipolocal(equipolocal);
    }

    /* equipoVisitante, PK */
    public String getEquipovisitante() {
        return equipovisitante;
    }

    /* equipoVisitante, PK */
    public void setEquipovisitante(String equipovisitante) {
        this.equipovisitante = equipovisitante;
        _key.setEquipovisitante(equipovisitante);
    }

    /* fecha */
    public java.util.Date getFecha() {
        return fecha;
    }

    /* fecha */
    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    /* reporte */
    public String getReporte() {
        return reporte;
    }

    /* reporte */
    public void setReporte(String reporte) {
        this.reporte = reporte;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Espiatienepartido))
            return false;

        Espiatienepartido bean = (Espiatienepartido) obj;

        if (this.aliasespia == null) {
            if (bean.aliasespia != null)
                return false;
        }
        else if (!this.aliasespia.equals(bean.aliasespia)) 
            return false;

        if (this.temporada == null) {
            if (bean.temporada != null)
                return false;
        }
        else if (!this.temporada.equals(bean.temporada)) 
            return false;

        if (this.nojornada != bean.nojornada)
            return false;

        if (this.equipolocal == null) {
            if (bean.equipolocal != null)
                return false;
        }
        else if (!this.equipolocal.equals(bean.equipolocal)) 
            return false;

        if (this.equipovisitante == null) {
            if (bean.equipovisitante != null)
                return false;
        }
        else if (!this.equipovisitante.equals(bean.equipovisitante)) 
            return false;

        if (this.fecha == null) {
            if (bean.fecha != null)
                return false;
        }
        else if (!this.fecha.equals(bean.fecha)) 
            return false;

        if (this.reporte == null) {
            if (bean.reporte != null)
                return false;
        }
        else if (!this.reporte.equals(bean.reporte)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Espiatienepartido bean = new Espiatienepartido();
        bean.aliasespia = this.aliasespia;
        bean.temporada = this.temporada;
        bean.nojornada = this.nojornada;
        bean.equipolocal = this.equipolocal;
        bean.equipovisitante = this.equipovisitante;
        if (this.fecha != null)
            bean.fecha = (java.util.Date) this.fecha.clone();
        bean.reporte = this.reporte;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("aliasespia").append(" = ").append(aliasespia).append("]").append(sep);
        sb.append("[").append("temporada").append(" = ").append(temporada).append("]").append(sep);
        sb.append("[").append("nojornada").append(" = ").append(nojornada).append("]").append(sep);
        sb.append("[").append("equipolocal").append(" = ").append(equipolocal).append("]").append(sep);
        sb.append("[").append("equipovisitante").append(" = ").append(equipovisitante).append("]").append(sep);
        sb.append("[").append("fecha").append(" = ").append(fecha).append("]").append(sep);
        sb.append("[").append("reporte").append(" = ").append(reporte).append("]").append(sep);
        return sb.toString();
    }
}