/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 23 23:16:19 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package Modelo;

/*
 * For Table Estado
 */
public class Estado implements java.io.Serializable, Cloneable {
    private EstadoKey _key = new EstadoKey();

    /* nombreEstado, PK */
    protected String nombreestado;

    /* Return the key object. */
    public EstadoKey getKeyObject() {
        return _key;
    }

    /* nombreEstado, PK */
    public String getNombreestado() {
        return nombreestado;
    }

    /* nombreEstado, PK */
    public void setNombreestado(String nombreestado) {
        this.nombreestado = nombreestado;
        _key.setNombreestado(nombreestado);
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Estado))
            return false;

        Estado bean = (Estado) obj;

        if (this.nombreestado == null) {
            if (bean.nombreestado != null)
                return false;
        }
        else if (!this.nombreestado.equals(bean.nombreestado)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Estado bean = new Estado();
        bean.nombreestado = this.nombreestado;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombreestado").append(" = ").append(nombreestado).append("]").append(sep);
        return sb.toString();
    }
}