/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon Apr 23 23:16:19 CDT 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package Modelo;

public class EstadoKey implements java.io.Serializable, Cloneable {
    /* nombreEstado */
    protected String nombreestado;

    /* nombreEstado */
    public String getNombreestado() {
        return nombreestado;
    }

    /* nombreEstado */
    public void setNombreestado(String nombreestado) {
        this.nombreestado = nombreestado;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (nombreestado != null)  
            hashCode += nombreestado.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof EstadoKey))
            return false;

        EstadoKey key = (EstadoKey) obj;

        if (this.nombreestado == null) {
            if (key.nombreestado != null)
                return false;
        }
        else if (!this.nombreestado.equals(key.nombreestado)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        EstadoKey key = new EstadoKey();
        key.nombreestado = this.nombreestado;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("nombreestado").append(" = ").append(nombreestado).append("]");
        return sb.toString();
    }
}